$(document).ready(function(){
	$("*").click(function(){
		$(this).animate({fontSize:"16px"},3000);
	});
	$("#textstyle1").click(function(){
		$(this).hide().show(1000);
	});
	$(".textstyle2").click(function(){
		$(this).animate({fontWeight:"800"},3000);
	});
	$("h1").click(function(){
		$(this).hide(1500).show(1500);
	});
	$("h1:first").click(function(){
		$(this).animate({fontSize:"32px"},3000);
	});
	$("span:last").click(function(){
		$(this).fadeOut(1500).fadeIn(1500).css({color:"orange"});
	});
	$("span:even").click(function(){
		$(this).slideUp(1500).slideDown(1500).css({color:"red"});
	});
	$("span:odd").mouseover(function(){
		$(this).css({color:"green"});
	});
	$("span:first-child").mouseenter(function(){
		$(this).css({fontStyle:"italic"});
	});
	$("span:last-child").click(function(){
		$(this).animate({marginLeft:"40px"},200);
		$(this).animate({marginLeft:"0px"},200);
	});
})